// =============================================================================
// RevertChange Use Case Tests — TDD Style
// =============================================================================
//
// THE CLIMAX TEST: Revert a change, verify NO email is sent.
//
import { describe, expect, it } from "@effect/vitest"
import { Effect, Layer } from "effect"

import { revertChange } from "../../src/usecases/RevertChange.js"
import { updateAddressField } from "../../src/usecases/UpdateAddressField.js"
import { createUser } from "../../src/usecases/CreateUser.js"
import { createAddress } from "../../src/usecases/CreateAddress.js"
import { InMemoryEventStores } from "../../src/infrastructure/InMemoryEventStore.js"
import { makeCaptureEmailService } from "../../src/infrastructure/ConsoleEmailService.js"
import { makeInMemoryRegistryLayer } from "../../src/infrastructure/InMemoryRegistry.js"
import { makeTestIdGenerator } from "../../src/IdGenerator.js"
import { IdGenerator } from "../../src/IdGenerator.js"
import { EmailService } from "../../src/EmailService.js"
import type { RevertToken } from "../../src/domain/address/State.js"

describe("RevertChange use case", () => {
  const makeTestLayer = () => {
    const emailCapture = makeCaptureEmailService()
    const layer = Layer.mergeAll(
      InMemoryEventStores,
      Layer.succeed(EmailService, emailCapture.service),
      makeInMemoryRegistryLayer(),
      Layer.succeed(IdGenerator, makeTestIdGenerator())
    )
    return { layer, emailCapture }
  }

  it.effect("reverts a city change and sends NO email", () =>
    Effect.gen(function* () {
      const { layer, emailCapture } = makeTestLayer()

      yield* Effect.gen(function* () {
        // Setup: create user and address
        yield* createUser({
          email: "jean@example.com" as any,
          firstName: "Jean" as any,
          lastName: "Dupont" as any
        })

        yield* createAddress({
          nickname: "jean-dupont",
          label: "home" as any,
          streetNumber: "42" as any,
          streetName: "Rue de Rivoli" as any,
          zipCode: "75001" as any,
          city: "Paris" as any,
          country: "France" as any
        })

        // Update city (this sends an email and creates a revert token)
        yield* updateAddressField({
          nickname: "jean-dupont",
          label: "home",
          field: "city",
          value: "Lyon"
        })

        // Get the revert token from registry
        // The token was generated by IdGenerator — with test generator it's predictable
        // test-1 = userId, test-2 = addressId, test-3 = createAddress revertToken
        // test-4 = updateAddressField revertToken
        const revertToken = "test-4" as RevertToken

        // Clear emails to isolate the revert
        emailCapture.clear()

        // Act: revert the change
        const result = yield* revertChange({ token: revertToken })

        // Assert: revert succeeded
        expect(result.reverted).toBe(true)
        expect(result.message).toContain("reverted")

        // Assert: NO EMAIL sent for correction!
        const emails = emailCapture.getSentEmails()
        expect(emails).toHaveLength(0)
      }).pipe(Effect.provide(layer))
    })
  )

  it.effect("fails with TokenNotFound for unknown token", () =>
    Effect.gen(function* () {
      const { layer } = makeTestLayer()

      yield* Effect.gen(function* () {
        const result = yield* revertChange({
          token: "nonexistent-token" as RevertToken
        }).pipe(Effect.either)

        expect(result._tag).toBe("Left")
        if (result._tag === "Left") {
          expect(result.left._tag).toBe("TokenNotFound")
        }
      }).pipe(Effect.provide(layer))
    })
  )

  it.effect("token can only be used once", () =>
    Effect.gen(function* () {
      const { layer } = makeTestLayer()

      yield* Effect.gen(function* () {
        // Setup
        yield* createUser({
          email: "jean@example.com" as any,
          firstName: "Jean" as any,
          lastName: "Dupont" as any
        })

        yield* createAddress({
          nickname: "jean-dupont",
          label: "home" as any,
          streetNumber: "42" as any,
          streetName: "Rue de Rivoli" as any,
          zipCode: "75001" as any,
          city: "Paris" as any,
          country: "France" as any
        })

        yield* updateAddressField({
          nickname: "jean-dupont",
          label: "home",
          field: "city",
          value: "Lyon"
        })

        const revertToken = "test-4" as RevertToken

        // First revert: should succeed
        const firstResult = yield* revertChange({ token: revertToken })
        expect(firstResult.reverted).toBe(true)

        // Second revert: should fail (token consumed)
        const secondResult = yield* revertChange({ token: revertToken }).pipe(Effect.either)
        expect(secondResult._tag).toBe("Left")
        if (secondResult._tag === "Left") {
          // Could be TokenNotFound (registry) or RevertTokenInvalid (domain)
          expect(["TokenNotFound", "RevertTokenInvalid"]).toContain(secondResult.left._tag)
        }
      }).pipe(Effect.provide(layer))
    })
  )

  it.effect("can revert address creation (CreationReverted)", () =>
    Effect.gen(function* () {
      const { layer, emailCapture } = makeTestLayer()

      yield* Effect.gen(function* () {
        // Setup
        yield* createUser({
          email: "jean@example.com" as any,
          firstName: "Jean" as any,
          lastName: "Dupont" as any
        })

        yield* createAddress({
          nickname: "jean-dupont",
          label: "home" as any,
          streetNumber: "42" as any,
          streetName: "Rue de Rivoli" as any,
          zipCode: "75001" as any,
          city: "Paris" as any,
          country: "France" as any
        })

        // The creation revert token is test-3 (test-1=userId, test-2=addressId, test-3=revertToken)
        const creationRevertToken = "test-3" as RevertToken

        emailCapture.clear()

        // Act: revert the creation
        const result = yield* revertChange({ token: creationRevertToken })

        // Assert
        expect(result.reverted).toBe(true)

        // No email for correction
        expect(emailCapture.getSentEmails()).toHaveLength(0)
      }).pipe(Effect.provide(layer))
    })
  )
})
